### ISSUE TITLE
Adding my first SAPL to a Spring Boot 2.6.4 projects results in class not found

### ISSUE THREAD

**Issue by GrantGochnauer** [heutelbeck/sapl-demos#49]
Hello - 

We are just starting to explore using SAPL and I have a simple Spring Boot 2.6.4 application using Gradle and have included SAPL like:
```
  // SAPL BOM
    implementation(platform("io.sapl:sapl-bom:2.0.1"))
    implementation 'io.sapl:sapl-spring-security'
    implementation 'io.sapl:sapl-spring-pdp-embedded'
```

However when I add my first SAPL file to the resources folder, I get the following stack trace:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.sapl.prp.PrpUpdateEventSource]: Factory method 'prpUpdateSource' threw exception; nested exception is java.lang.NoSuchFieldError: EOF_TOKEN
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 98 common frames omitted
Caused by: java.lang.NoSuchFieldError: EOF_TOKEN
	at org.eclipse.xtext.parser.antlr.Lexer.nextToken(Lexer.java:60)
	at org.antlr.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:143)
	at org.antlr.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:137)
```

and it appears that the version of antlr that is included is missing a reference to:
`Token.EOF_TOKEN;` in the `Lexar` class.

It doesn't appear that you've added anything special here:
https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-mvc-app/pom.xml

Perhaps something with the latest Spring Boot?
Thanks

**Comment by GrantGochnauer** [comment]
Running a quick dependency check, `gradle -q dependencies`, it looks like antlr 4.9.2 is being pulled in via the Netflix DGS framework which is our GraphQL library that we're using in this simple example. It looks like SAPL uses Antlr 3.x series.

```
|    +--- com.netflix.graphql.dgs:graphql-dgs-platform:4.9.22 (*)
|    +--- com.netflix.graphql.dgs:graphql-dgs-spring-boot-oss-autoconfigure:4.9.22
|    |    +--- org.springframework:spring-web:5.2.18.RELEASE -> 5.3.16 (*)
|    |    +--- org.springframework.boot:spring-boot-starter:2.3.12.RELEASE -> 2.6.4 (*)
|    |    +--- org.apache.commons:commons-lang3:3.10 -> 3.12.0
|    |    +--- com.netflix.graphql.dgs:graphql-dgs-platform:4.9.22 (*)
|    |    +--- com.netflix.graphql.dgs:graphql-dgs:4.9.22
|    |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.5.32 -> 1.6.10
|    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.6.10
|    |    |    |         +--- org.jetbrains:annotations:13.0
|    |    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.6.10
|    |    |    +--- org.springframework:spring-web:5.2.18.RELEASE -> 5.3.16 (*)
|    |    |    +--- org.springframework:spring-context:5.2.18.RELEASE -> 5.3.16 (*)
|    |    |    +--- com.fasterxml.jackson.module:jackson-module-kotlin:2.12.5 -> 2.13.1
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.1 (*)
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.1 (*)
|    |    |    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.5.30 -> 1.6.10 (*)
|    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.13.1 -> 2.13.2 (*)
|    |    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.5 -> 2.13.2 (*)
|    |    |    +--- com.apollographql.federation:federation-graphql-java-support:0.7.0
|    |    |    |    +--- com.apollographql.federation:federation-graphql-java-support-api:0.7.0
|    |    |    |    +--- com.graphql-java:graphql-java:17.3
|    |    |    |    |    +--- org.antlr:antlr4-runtime:4.9.2 -> 4.9.3
|    |    |    |    |    +--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
|    |    |    |    |    +--- com.google.guava:guava:30.0-jre -> 31.1-jre
|    |    |    |    |    |    +--- com.google.guava:failureaccess:1.0.1
|    |    |    |    |    |    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |    |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    |    |    |    +--- org.checkerframework:checker-qual:3.12.0 -> 3.19.0
|    |    |    |    |    |    +--- com.google.errorprone:error_prone_annotations:2.11.0
|    |    |    |    |    |    \--- com.google.j2objc:j2objc-annotations:1.3
|    |    |    |    |    +--- com.graphql-java:java-dataloader:3.1.0
|    |    |    |    |    |    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36
|    |    |    |    |    +--- org.reactivestreams:reactive-streams:1.0.2 -> 1.0.3
|    |    |    |    |    \--- org.antlr:antlr4:4.9.2
|    |    |    |    |         +--- org.antlr:antlr4-runtime:4.9.2 -> 4.9.3
|    |    |    |    |         +--- org.antlr:antlr-runtime:3.5.2
|    |    |    |    |         +--- org.antlr:ST4:4.3
|    |    |    |    |         |    \--- org.antlr:antlr-runtime:3.5.2
|    |    |    |    |         +--- org.abego.treelayout:org.abego.treelayout.core:1.0.3
|    |    |    |    |         +--- org.glassfish:javax.json:1.0.4
|    |    |    |    |         \--- com.ibm.icu:icu4j:61.1
```

**Comment by GrantGochnauer** [comment]
I added antlr runtime 3.2 specifically (so now I have 3.x and 4.x) and got a little further. 

```
Caused by: io.sapl.api.interpreter.PolicyEvaluationException: Parsing errors: [XtextSyntaxDiagnostic: null:1 no viable alternative at input '﻿']
	at io.sapl.interpreter.DefaultSAPLInterpreter.loadAsResource(DefaultSAPLInterpreter.java:140)
	at io.sapl.interpreter.DefaultSAPLInterpreter.parse(DefaultSAPLInterpreter.java:65)
	at io.sapl.interpreter.DefaultSAPLInterpreter.parse(DefaultSAPLInterpreter.java:60)
	at io.sapl.prp.resources.ResourcesPrpUpdateEventSource.parseAndCreatePublicationUpdate(ResourcesPrpUpdateEventSource.java:92)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
```

My only policy looks like this:
```
import filter.*

set "SimpleMVCSecurityController"
first-applicable


/*
 * This 'for' statement ensures, that the policies are only checked when they are actions, e.g., method calls,
 * in the designated Java class.
 * In this case, spring will indirectly implement the PatientRepository interface and it may not appear directly
 * in the method signatures, e.g. when using default methods from CrudRepositories. Thus we inspect the class
 * hierarchy and interfaces implemented by the class to scope the policy set.
 */
for "SimpleMVCSecurityController" in action.java.instanceof..simpleName

/*
 * This policy enables all authenticated users to call the getDocument endpoint.
 */
policy "all authenticated users may call the get document endpoint"
permit action.java.name == "getDocument" & resource.http.requestedURI == "/getDocument"
where
	!("ROLE_ANONYMOUS" in subject..authority);
```

The downside of including antlr 3.2 is that it's from 2009. I checked the upstream eclipse project and it looks like later versions of xtext are also still on 3.2 sadly/

**Comment by heutelbeck** [comment]
Hello Grant,

I generally bumped the demo dependencies to Spring Boot 2.6.4. This version is fully supported.

For replication of the issue, you found I added the following dependency to the sapl-demo-mvc-app:

```xml
<dependency>
	<groupId>com.netflix.graphql.dgs</groupId>
	<artifactId>graphql-dgs-spring-boot-starter</artifactId>
	<version>4.9.16</version>
</dependency>
```

Then I added your policy to the policies folder in the resources.

Then I added the following GraphQL schema, linking to the demo domain:

```graphql
type Query {
    patient(id: Int): Patient
}

type Patient {     
    id: Int
    medicalRecordNumber: String
	icd11Code: String
	diagnosisText: String
	attendingDoctor: String
	attendingNurse: String
	phoneNumber: String
	roomNumber: String
}
```

Then the matching datafetcher is implemented as follows:

```java
@DgsComponent
@RequiredArgsConstructor
public class PatientsDatafetcher {

	private final PatientRepository patientsRepository;

	@DgsQuery
	public Patient patient(@InputArgument long id) {
		return patientsRepository.findById(id).orElse(null);
	}
}
```

With these changes:
- The application starts (i.e., your policy loads without error)
- The GraphQL Playground works and queries can be made (after authentications)
- The policies as defined for the underlying data repository are enforced. E.g., when authenticated as 'horst' some data of the patient will be blackened.

Some comments:
- Yes, XText is a slow-moving project, and a current ANTLR implementation would be appreciated. Sadly this is outside our scope of control. During testing your issue, I tried to just replace the 3.2.x Version with the 4.9.x. These are not compatible. However, they appear to be happy to live side by side in the same project.
- The issue you report appears to be from some other circumstance in the project. I am happy to take another look with some additional details.

**Comment by GrantGochnauer** [comment]
Thank you! Let me work to isolate the issue a bit more on my side. I must be bringing in some other dependency or some other setup issue. Stay tuned.

**Comment by heutelbeck** [comment]
Just as a further comment: Starting with Spring Boot 2.7.0 there will be new GraphQL starter:

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-graphql</artifactId>
</dependency>
```

**Comment by heutelbeck** [comment]
Likely reason for issue: SAPL policy file started with an UTF byte order mark 0xEFBBBF.

For now please encode the policies to not have the byte order mark.

I will schedule an improvement for 2.1.0 to make the parser more robust in presence of such encodings.
